[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_ENV = "production"

[context.production.environment]
  NODE_VERSION = "18.18.2"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
